# Generated by Django 5.2.14 on 2026-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código de ligação com o Mercado Livre.', max_length=50, unique=True, verbose_name='SKU')),
                ('nome', models.CharField(help_text='Descrição da autopeça.', max_length=150, verbose_name='Nome')),
                ('codigo_barras_ean', models.CharField(blank=True, help_text='Requisito forte para exposição no Mercado Livre.', max_length=14, verbose_name='Código de Barras EAN')),
                ('marca', models.CharField(help_text='Evita devoluções por incompatibilidade da peça.', max_length=50, verbose_name='Marca')),
                ('ncm', models.CharField(help_text='Nomenclatura fiscal da peça.', max_length=8, verbose_name='NCM')),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Valor base para emissão da nota.', max_digits=10, verbose_name='Preço de Venda')),
                ('quantidade_estoque', models.IntegerField(default=0, help_text='Saldo atual do item.', verbose_name='Quantidade em Estoque')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
