# Generated by Django 5.2.14 on 2026-05-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de aquisição da autopeça.', max_digits=10, verbose_name='Preço de Custo'),
        ),
    ]
