# Generated by Django 5.2.14 on 2026-05-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_produto_preco_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade de itens da nova compra.', verbose_name='Quantidade Comprada')),
                ('preco_custo', models.DecimalField(decimal_places=2, help_text='Valor unitário pago nesta compra.', max_digits=10, verbose_name='Preço de Custo Unitário')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data da Entrada')),
                ('observacao', models.TextField(blank=True, help_text='Ex: Nome do Fornecedor, Número da Nota Fiscal, etc.', verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='catalogo.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Entrada de Estoque',
                'verbose_name_plural': 'Entradas de Estoque',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
