# Generated by Django 5.2.14 on 2026-05-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_entradaestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogo.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='catalogo.categoria', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='CompatibilidadeProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_carro', models.CharField(max_length=100, verbose_name='Marca do Carro')),
                ('modelo_carro', models.CharField(max_length=100, verbose_name='Modelo do Carro')),
                ('ano_carro', models.CharField(blank=True, max_length=50, verbose_name='Ano / Versão')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='catalogo.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Compatibilidade de Produto',
                'verbose_name_plural': 'Compatibilidades de Produtos',
                'ordering': ['marca_carro', 'modelo_carro'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada (Compra)'), ('S', 'Saída (Venda/Ajuste)'), ('A', 'Ajuste Manual')], max_length=1, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Movimentada')),
                ('saldo_anterior', models.IntegerField(verbose_name='Saldo Anterior')),
                ('saldo_atual', models.IntegerField(verbose_name='Saldo Atual')),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Origem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='catalogo.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
    ]
