# Generated by Django 5.2.14 on 2026-05-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_maximo',
            field=models.IntegerField(default=0, help_text='Capacidade máxima de armazenamento. 0 = sem limite.', verbose_name='Estoque Máximo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=5, help_text='Alerta quando o estoque atingir esse valor.', verbose_name='Estoque Mínimo'),
        ),
    ]
