# Generated by Django 5.2.14 on 2026-05-28 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_add_estoque_minimo_maximo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tabela de Preço')),
                ('percentual_desconto_padrao', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de desconto automático aplicado a todos os produtos nesta tabela (ex: 10.00). Use valor negativo para acréscimo.', max_digits=5, verbose_name='Desconto Padrão (%)')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preços',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_fabricante',
            field=models.CharField(blank=True, help_text='Código de referência do fabricante da autopeça.', max_length=50, null=True, verbose_name='Código do Fabricante (Part Number)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Associe a um produto pai se este item for uma variação física (ex: Lado Esquerdo/Direito).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalogo.produto', verbose_name='Produto Pai'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('PÇ', 'Peça'), ('JG', 'Jogo'), ('L', 'Litro'), ('KG', 'Quilograma'), ('CX', 'Caixa'), ('KT', 'Kit')], default='UN', help_text='Unidade de comercialização do item.', max_length=10, verbose_name='Unidade de Medida'),
        ),
        migrations.CreateModel(
            name='PrecoProdutoTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Defina um preço fixo específico para este produto nesta tabela. Se deixado como 0.00 ou em branco, será usado o desconto percentual da tabela.', max_digits=10, verbose_name='Preço de Venda Customizado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_tabelas', to='catalogo.produto', verbose_name='Produto')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='catalogo.tabelapreco', verbose_name='Tabela de Preço')),
            ],
            options={
                'verbose_name': 'Preço do Produto por Tabela',
                'verbose_name_plural': 'Preços dos Produtos por Tabelas',
                'unique_together': {('tabela', 'produto')},
            },
        ),
    ]
