# Generated by Django 5.2.14 on 2026-05-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_tabelapreco_produto_codigo_fabricante_produto_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('PÇ', 'Peça'), ('JG', 'Jogo'), ('L', 'Litro'), ('KG', 'Quilograma'), ('CX', 'Caixa'), ('KT', 'Kit')], default='UN', help_text='Unidade de comercialização do item.', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
