# Generated by Django 5.2.14 on 2026-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_origem', models.CharField(default='SP', help_text='Identifica o estado de saída da mercadoria.', max_length=2, verbose_name='UF Origem')),
                ('uf_destino', models.CharField(help_text='Identifica o estado do comprador.', max_length=2, verbose_name='UF Destino')),
                ('ncm', models.CharField(blank=True, help_text='Define qual NCM a regra afeta.', max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(help_text='Código Fiscal de Operações a ser aplicado.', max_length=4, verbose_name='CFOP')),
                ('csosn', models.CharField(blank=True, help_text='Código de situação tributária (se Simples Nacional).', max_length=4, verbose_name='CSOSN')),
                ('cst', models.CharField(blank=True, help_text='Código de situação tributária (se Lucro Real/Presumido).', max_length=3, verbose_name='CST')),
            ],
            options={
                'verbose_name': 'Matriz Tributária',
                'verbose_name_plural': 'Matrizes Tributárias',
                'ordering': ['uf_origem', 'uf_destino', 'ncm'],
            },
        ),
    ]
